(()=>{
const $=id=>document.getElementById(id),pulse=$('statusPulse'),timeline=$('timeline');let pt=0,last='';
const vib=p=>{try{navigator.vibrate?.(p)}catch{}},flash=(k='echo',ms=150)=>{if(!pulse)return;clearTimeout(pt);pulse.className=`status-pulse show ${k}`;pt=setTimeout(()=>pulse.className='status-pulse',ms)},save=()=>{try{return JSON.parse(localStorage.getItem('echoSave')||'{}')}catch{return {}}};
function sync(){const n=$('echoChips')?.querySelectorAll('.echo-chip').length||0;if($('echoBadge'))$('echoBadge').textContent=`${n} ÉCHO${n>1?'S':''}`;if($('loopBadge'))$('loopBadge').textContent=`BOUCLE ${String(n+1).padStart(2,'0')}`;const sh=$('shardCount'),d=[];if(sh&&!sh.classList.contains('hidden')&&sh.textContent.trim())d.push(sh.textContent.trim());if(n)d.push(`${n} ÉCHO${n>1?'S':''}`);if($('objectiveProgress'))$('objectiveProgress').textContent=d.length?d.join(' · '):'PROTOCOLE ACTIF';const t=parseFloat(($('timerText')?.textContent||'99').replace(',','.'));timeline?.classList.toggle('urgent',Number.isFinite(t)&&t<=5)}
function campaign(){const s=save()||{},done=Object.values(s.stars||{}).filter(v=>+v>0).length,u=Math.max(1,Math.min(30,+s.unlocked||1));if($('campaignFill'))$('campaignFill').style.width=`${Math.min(100,done/30*100)}%`;if($('campaignLabel'))$('campaignLabel').textContent=done>=30?'CAMPAGNE STABILISÉE':'CAMPAGNE';if($('continueHint'))$('continueHint').textContent=done>=30?'PROTOCOLE FINAL TERMINÉ':`PROTOCOLE ${String(u).padStart(2,'0')}`}
function victory(){if($('winScreen')?.classList.contains('hidden'))return;const e=+$('statEchoes')?.textContent||0,t=$('statTime')?.textContent||'—';if($('performanceNote'))$('performanceNote').textContent=e===0?'CHRONOLOGIE PARFAITE':e<=2?'EXÉCUTION PRÉCISE':'CHRONOLOGIE STABILISÉE';if($('parInfo'))$('parInfo').textContent=`${e} ÉCHO${e>1?'S':''} · ${t}`;flash('win',420);vib([18,35,18]);campaign()}
document.addEventListener('pointerdown',e=>{const id=e.target.closest('button')?.id;if(['sealBtn','touchSealBtn'].includes(id)){flash('echo',190);vib(14)}else if(id==='dashBtn'){flash('dash',120);vib(9)}else if(id==='interactBtn'){flash('portal',110);vib(7)}},{passive:true});
document.addEventListener('keydown',e=>{if(e.repeat)return;if(e.code==='KeyR'){flash('echo',190);vib(12)}else if(e.code.startsWith('Shift')){flash('dash',110);vib(8)}else if(['KeyE','Space'].includes(e.code))flash('portal',100);else if(e.code==='Enter'){if(!$('pauseScreen')?.classList.contains('hidden'))$('resumeBtn')?.click();else if(!$('winScreen')?.classList.contains('hidden'))$('nextBtn')?.click()}});
const toast=$('toast');if(toast)new MutationObserver(()=>{const x=toast.textContent.trim();if(!x||x===last)return;last=x;if(/FRACTURE|DANGER/i.test(x)){flash('danger',260);vib([26,25,26]);document.body.animate([{transform:'translate(0)'},{transform:'translate(-3px,2px)'},{transform:'translate(3px,-1px)'},{transform:'translate(0)'}],{duration:150})}else if(/FRAGMENT|ACTIV|OUVERT/i.test(x)){flash('portal',160);vib(10)}else if(/ÉCHO|SCELL/i.test(x)){flash('echo',180);vib(12)}sync()}).observe(toast,{childList:true,subtree:true,characterData:true});
if($('echoChips'))new MutationObserver(sync).observe($('echoChips'),{childList:true,subtree:true});if($('winScreen'))new MutationObserver(victory).observe($('winScreen'),{attributes:true,attributeFilter:['class']});
setInterval(sync,250);campaign();sync();window.__ECHO_REFORGED__={version:'4.0-reforged',enhanced:true};
})();
